#!/bin/bash

echo 'execute this script on "./RESULTS" folder generated by "./batch_lstm_job.sh". Press ctrl+c to exit if you havent requirements ...'

sleep 5

for i in $(ls -G +(pe|de|pb|fcf|peg)*_+(MCD|DIS|INTC|AAPL|MSFT|WDC)* | grep ':' | sed  's/://' - ); do ffmpeg -framerate 1 -i ${i}/predict/predictEpoch%d.png -c:v libvpx-vp9 -vf "drawtext=fontfile=Arial.ttf: text='%{eif\:(n+1)*10\:d} epochs': x=(w-tw)/2: y=h-(2*lh): fontcolor=black: box=1: boxcolor=0x00000000"  video/${i}.webm; popd; done
