[default]
extra_input = ['sentiment', 'pe']
tickers = ['MCD', 'DIS', 'INTC', 'AAPL', 'MSFT', 'WDC']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 90

# https://www.investopedia.com/articles/fundamental-analysis/09/five-must-have-metrics-value-investors.asp
[pe_MCD]
extra_input = ['pe']
tickers = ['MCD']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7

[pb_MCD]
extra_input = ['pb']
tickers = ['MCD']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[de_MCD]
extra_input = ['de']
tickers = ['MCD']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[peg_MCD]
extra_input = ['eps']
tickers = ['MCD']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7



[fcf_MCD]
extra_input = ['fcf']
tickers = ['MCD']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[pe_DIS]
extra_input = ['pe']
tickers = ['DIS']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7

[pb_DIS]
extra_input = ['pb']
tickers = ['DIS']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[de_DIS]
extra_input = ['de']
tickers = ['DIS']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[fcf_DIS]
extra_input = ['fcf']
tickers = ['DIS']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[peg_DIS]
extra_input = ['eps']
tickers = ['DIS']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7



[pe_INTC]
extra_input = ['pe']
tickers = ['INTC']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7

[pb_INTC]
extra_input = ['pb']
tickers = ['INTC']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[de_INTC]
extra_input = ['de']
tickers = ['INTC']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[fcf_INTC]
extra_input = ['fcf']
tickers = ['INTC']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[peg_INTC]
extra_input = ['eps']
tickers = ['INTC']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7



[pe_AAPL]
extra_input = ['pe']
tickers = ['AAPL']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7

[pb_AAPL]
extra_input = ['pb']
tickers = ['AAPL']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[de_AAPL]
extra_input = ['de']
tickers = ['AAPL']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7

[fcf_AAPL]
extra_input = ['fcf']
tickers = ['AAPL']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[peg_AAPL]
extra_input = ['eps']
tickers = ['AAPL']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[pe_MSFT]
extra_input = ['pe']
tickers = ['MSFT']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7

[pb_MSFT]
extra_input = ['pb']
tickers = ['MSFT']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[de_MSFT]
extra_input = ['de']
tickers = ['MSFT']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7

[fcf_MSFT]
extra_input = ['fcf']
tickers = ['MSFT']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7




[peg_MSFT]
extra_input = ['eps']
tickers = ['MSFT']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[pe_WDC]
extra_input = ['pe']
tickers = ['WDC']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7

[pb_WDC]
extra_input = ['pb']
tickers = ['WDC']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[de_WDC]
extra_input = ['de']
tickers = ['WDC']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7

[fcf_WDC]
extra_input = ['fcf']
tickers = ['WDC']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7


[peg_WDC]
extra_input = ['eps']
tickers = ['WDC']
BATCH_SIZE = 90
LOSS = 'mae'
N_HIDDEN = 1000
NUM_EPOCHS = 100
SAVE_EVERY = 10
NUM_TIMESTEPS = 180
LEARNING_RATE = 0.001
BEGINNING_DATE = '2013-03-31'
ENDING_DATE = '2018-06-31'
TIMESTEPS_AHEAD = 7
